services:
  #http://localhost:9090/query - gui
  prometheus:
    image: prom/prometheus:latest 
    container_name: prometheus
    volumes:
      - "C:/Users/ivan/Documents/.docker-compose/OpenTelemetryStack/files/collector/prometheus.yml:/etc/prometheus/prometheus.yml"
      # - "C:/Users/ivan/Documents/.docker-compose/OpenTelemetryStack/files/collector/prometheus.yml:/etc/prometheus/prometheus.yml"
      # - ./prometheus:/etc/prometheus/
    command:
      - '--enable-feature=otlp-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  #http://localhost:3010/login - gui
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3010:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - C:/Users/ivan/Documents/.docker-compose/OpenTelemetryStack/files/collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    command: ["--config", "/etc/otel-collector-config.yml"]
    ports:
      - "9464:9464"   # Port for Prometheus to scrape
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge