receivers:
  otlp:
    protocols:
      grpc:
      http:

  prometheus:
    config:
      scrape_configs:
        - job_name: "my_izi_service_to_scrap"
          scrape_interval: 5s
          static_configs:
            - targets: ["host.docker.internal:5238"]

processors:
  batch:


exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"  # Port where Prometheus can scrape metrics

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]
